name: expense_tracker_pro
description: "Surge - Track your expenses effortlessly"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.5
  async: ^2.11.0
  
  # Code Generation Annotations
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  
  # Navigation
  go_router: ^14.2.0
  
  # Local Database
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2
  
  # UI & Utilities
  fl_chart: ^1.1.1
  intl: ^0.19.0
  uuid: ^4.3.3
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  image_picker: ^1.2.1
  google_mlkit_text_recognition: ^0.15.0
  permission_handler: ^12.0.1
  share_plus: ^12.0.1
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2
  local_auth: ^2.3.0
  flutter_secure_storage: ^9.2.2
  
  # Firebase
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.3.8
  shared_preferences: ^2.3.4
  telephony: ^0.2.0
  pdf: ^3.11.3
  printing: ^5.14.2
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.0
  tflite_flutter: ^0.12.1
  image: ^4.3.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  
  # Generators
  build_runner: ^2.4.8
  riverpod_generator: ^2.4.0
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/surge_ai_logo.png
    - assets/models/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#C7F25E"
  adaptive_icon_foreground: "assets/images/app_icon.png"
